# Generated by Django 5.1.4 on 2025-01-30 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay_Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Position', models.CharField(choices=[('SK Chairman', 'SK Chairman'), ('SK Kagawad', 'SK Kagawad'), ('Brgy Captain', 'Brgy Captain'), ('Brgy Secretary', 'Brgy Secretary')], max_length=100)),
                ('StartDate_Term', models.DateField()),
                ('End_Term', models.DateField()),
                ('Contact_Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Barangay_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=100)),
                ('Project_Type', models.CharField(choices=[('Job Fairs and Training', 'Job Fairs and Training'), ('Education', 'Education'), ('Infrastructure', 'Infrastructure'), ('Sports Activities', 'Sports Activities')], max_length=100)),
                ('Description', models.TextField()),
                ('Project_Budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Start_Date', models.DateTimeField()),
                ('End_Date', models.DateTimeField()),
                ('Current_Status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Peding', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('Project_Leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barangay_official')),
            ],
        ),
        migrations.CreateModel(
            name='Barangay_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Type', models.CharField(choices=[('Health Service', 'Health Service'), ('Education and training Service', 'Education and Training'), ('Social Service', 'Social Service'), ('Environmental Services', 'Environmental Services')], max_length=100)),
                ('Description', models.TextField()),
                ('Venue', models.CharField(max_length=100)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Officials_Involved', models.ManyToManyField(to='app.barangay_official')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Filed', models.DateTimeField()),
                ('Complaint_Type', models.CharField(choices=[('Noise', 'Noise'), ('Waste management', 'Waste management'), ('Illegal Activities', 'Illegal Activities')], max_length=100)),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('Resolved', 'Resolved'), ('Pending', 'Pending')], max_length=100)),
                ('Action_Take', models.CharField(max_length=200)),
                ('Resident_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_Type', models.CharField(choices=[('Business Permit', 'Business Permit'), ('Clearance', 'Clearance'), ('Certificate of Indigency', 'Certificate of Indigency')], max_length=100)),
                ('Status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing')], max_length=100)),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barangay_official')),
                ('Requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
